### ISSUE TITLE
Dockerize using brainlife/dipy container?

### ISSUE THREAD

**Issue by soichih** [kitchell/app-converttck2trk#1]
The dipy container (brainlife/dipy) used to run various dipy app comes with h5py and nipype

$ RUN pip install numpy cython scipy matplotlib h5py nibabel nipype

We should be able to run this app using this container and run it on most of our computing resources (slurm1/2, etc..). This app is currently only enabled on Karst.

**Comment by kitchell** [comment]
We were working on doing just that a while ago, and I think it was not working for some reason. I don't remember if it was solved or not. I think probably not because it is not dockerized. but I may have run out of time to work on it.

**Comment by kitchell** [comment]
wait it is dockerized in a sense. from the main file: singularity exec -e docker://brainlife/dipy:0.13 ./main.py

**Comment by kitchell** [comment]
the app runs on my carbonate account, so I think you can enable it on everything now.

**Comment by soichih** [comment]
Ah, sorry I should have checked! 

OK I have enabled it on carbonate, slurm1 and slurm2.
